  # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: bumper bot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      TOKEN1: ODEyNzA1NTA3ODgyMDQxMzY1.YDky7Q.QzMxOI4lHB6vUg6y_AywgCw9AsE
      TOKEN2: NzkyMDQ3MDI0NDA0MDM3NjYy.YDkz-Q.dCwOSS59QFAoX8Zl6uRMoNZ3O3c
      TOKEN3: NzkyMDYzMDE1NDgxOTAxMTA2.YDk0iA.FKsru6mK2iY3GP9ajsklNmSLG-4
      PINGERID: 478321260481478677
    
    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: node bumpers.js
